version: '2'
services:
  pcache:
    image: registry.aspc.me/aspcartman/pcache
    ports:
      - "8080:8080"
    volumes:
      - "./data:/var/pcache"
    command: -store=/var/pcache/store.boltdb
# test
